### ISSUE TITLE
How could i request the information from my pc?

### ISSUE THREAD

**Issue by jorgrde1** [dalehumby/PiJuice-MQTT#2]
Im implementing this on my raspberry and I am not having any problems but how could I get the information that my raspberry publish from my pc?

**Comment by bastgau** [comment]
You can use a MQTT client like https://mqttx.app/
You can use an open source home automation like : Home Assistant (https://www.home-assistant.io/)

**Comment by dalehumby** [comment]
Hi @jorgrde1. I am not sure how familiar you are with the [MQTT](https://mqtt.org/) protocol?

This "PiJuice-MQTT" software is an MQTT Client, and _publishes_ data about the PiJuice (like battery voltage) to an MQTT Broker. The broker software that I use is [Mosquitto](https://mosquitto.org/).

As @bastgau pointed out, you'll then need another MQTT Client on your PC to _subscribe_ to the data feed. Some clients are https://mqttx.app/, Home Assistant, or you can even write your own client in Python or another programming language.

**Comment by jorgrde1** [comment]
Hi, I have already solved my issue and getting data from my PI via mqtt, thank you for the comments.
